/**
 * Phase 0 ΓÇö invite-only Flip-native staging PDS spike.
 *
 * These constants keep staging config out of production paths.
 * Nothing in this file is used by production code until Phase 1.
 *
 * Sign-in flow: use the existing hidden "Server (optional)" field on the
 * sign-in screen (mode=full, showAppPassword=true) and enter FLIP_STAGING_PDS_HOST.
 */

/** Hostname of the Flip invite-only staging PDS. */
export const FLIP_STAGING_PDS_HOST = 'staging.flip.app';

/** Full service URL for direct ATProto API calls to the staging PDS. */
export const FLIP_STAGING_PDS_URL = 'https://staging.flip.app';

/**
 * Handle suffix used by accounts created on the staging PDS.
 * e.g. alice.staging.flip.app
 */
export const FLIP_STAGING_HANDLE_SUFFIX = '.staging.flip.app';

/**
 * Phase 0 is invite-only. This invite code placeholder must be replaced
 * with a real code generated by the staging PDS admin before use.
 */
export const FLIP_STAGING_INVITE_CODE_PLACEHOLDER = 'flip-staging-XXXX-XXXX';
